# Étape 1 : Build (installation des dépendances)
FROM node:14 AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

# Étape 2 : Exécution
FROM node:14-alpine AS runtime

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app ./

EXPOSE 7777

CMD ["npm", "run", "start"]