CREATE TABLE games (
	gameId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	player1UUID TEXT NOT NULL,
	player2UUID TEXT NOT NULL,
	"start" TEXT,
	"end" TEXT,
	tournamentId INTEGER,
	CONSTRAINT games_FK FOREIGN KEY (player2UUID) REFERENCES players(playerUUID) ON UPDATE CASCADE,
	CONSTRAINT games_FK_1 FOREIGN KEY (player1UUID) REFERENCES players(playerUUID) ON UPDATE CASCADE,
	CONSTRAINT games_FK_2 FOREIGN KEY (tournamentId) REFERENCES tournaments(tournamentId) ON UPDATE CASCADE
);

CREATE TABLE players (
	playerUUID TEXT(128) NOT NULL UNIQUE,
	avatarProfile TEXT(256) NOT NULL DEFAULT 'panda.png',
	email TEXT(256) NOT NULL UNIQUE,
	pseudo TEXT(100) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	avgAccuracy INTEGER NOT NULL DEFAULT 0,
	killPerSeconde FLOAT NOT NULL DEFAULT 0,
	totalScore INTEGER NOT NULL DEFAULT 0,
	numberOfWin INTEGER NOT NULL DEFAULT 0,
	numberOfLoose INTEGER NOT NULL DEFAULT 0, 
	numberOfSoloGamePlay INTEGER NOT NULL DEFAULT 0,
	numberOfGameWithStrike INTEGER NOT NULL DEFAULT 0,
	bestStrike INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT players_PK PRIMARY KEY (playerUUID)
);

CREATE TABLE tournaments (
	tournamentId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT(128) NOT NULL
);

CREATE TABLE friendsRequest (
	friendsRequestId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	requestingPlayerUUID TEXT(128) NOT NULL,
	requestedPlayerUUID TEXT(128) NOT NULL,
	CONSTRAINT friendsRequestFK1 FOREIGN KEY (requestingPlayerUUID) REFERENCES players(playerUUID) ON UPDATE CASCADE,
	CONSTRAINT friendsRequestFK2 FOREIGN KEY (requestedPlayerUUID) REFERENCES players(playerUUID) ON UPDATE CASCADE
);

CREATE TABLE friends (
	friendsId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	player1UUID TEXT(128) NOT NULL,
	player2UUID TEXT(128) NOT NULL,
	CONSTRAINT friendsFK1 FOREIGN KEY (player1UUID) REFERENCES players(playerUUID) ON UPDATE CASCADE,
	CONSTRAINT friendsFK2 FOREIGN KEY (player2UUID) REFERENCES players(playerUUID) ON UPDATE CASCADE
);

CREATE TABLE trackingGames (
	trackingGameId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	playerUUID TEXT(128) NOT NULL,
	accuracy INTEGER NOT NULL DEFAULT 0,
	totalScore INTEGER NOT NULL DEFAULT 0,
	gameDate DATE NOT NULL,
	CONSTRAINT trackingGamesFK1 FOREIGN KEY (playerUUID) REFERENCES players(playerUUID) ON UPDATE CASCADE
);

CREATE TABLE gridGames (
	gridGamesId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	playerUUID TEXT(128) NOT NULL,
	accuracy INTEGER NOT NULL DEFAULT 0,
	totalScore INTEGER NOT NULL DEFAULT 0,
	killPerSeconde FLOAT NOT NULL DEFAULT 0,
	gameDate DATE NOT NULL,
	bestStrike INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT gridGamesIdFK1 FOREIGN KEY (playerUUID) REFERENCES players(playerUUID) ON UPDATE CASCADE
);
