name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fix package.json for ESM
        run: |
          jq '. + { "type": "module" }' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Run tests
        run: npm test
